defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: True
# Override at launch to select a GPU, for example: device=cuda:7
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 1200000000 # max frame
enable_eval: false
record_eval_video: false
eval_interval: 500 # evaluate the policy for every N training steps
save_interval: 500

# Training Environment
env:
  num_envs: 2048 # Number of drones for training
  max_episode_length: 2200
  env_spacing: 8.0 
  num_obstacles: 350

env_dyn:
  num_obstacles: 80 # set to zero if static env is needed
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

timing:
  enabled: true
  mode: overlapping_transport
  randomize_in_eval: true
  reference_dt: 0.016
  inference_delay:
    min: 0.016
    max: 0.096
    eval: 0.032
  command_delay:
    min: 0.016
    max: 0.032
    eval: 0.016
  change_probability: 0.2
  max_step_change: 1

viewer:
  eye: [0., 40., 40.]
  lookat: [0., 2.5, 0.]
  resolution: [960, 720]

wandb:
  project: End_to_End_Navigation_4090_PPO
  name: ppo_delay
  entity: null
  mode: online
