"""Five-frame autoregressive geometry-guided diffusion on fixed NavRL test starts.

The final LiDAR at every horizon is generated by the existing 20-step DDIM
UNet/VAE. A causal action-to-pose model only supplies a noised initialization.
The diffusion's ego features remain frozen as in the original 5/10-frame test,
so the comparison isolates geometric sampling guidance.
"""

import argparse
import json
import sys
from pathlib import Path

import h5py
import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lidar_wam.runner import stage1
from lidar_wam.runner.lidar_geometry import load_rays, warp_frame
from evaluate_lagen_metrics_10 import lidar_metric, summarize
from evaluate_representative import fetch, save_json
from try_epona_motion import next_state, transform_from_initial
from try_epona_guided_diffusion import load_motion

ROOT = Path(__file__).resolve().parents[1]


def paired_summary(rows, methods, horizon):
    selected = [r for r in rows if r["horizon"] == horizon]
    groups = {"all": selected}
    for seed in sorted({r["seed"] for r in selected}):
        groups[f"seed_{seed}"] = [r for r in selected if r["seed"] == seed]
    output = {}
    for name, group in groups.items():
        paired = [r for r in group if all(not r[m]["empty_cloud"] for m in methods)]
        output[name] = {
            "total": len(group), "paired_nonempty": len(paired),
            "paired_cd_paper_m2": {m: float(np.mean([
                r[m]["cd_paper_m2"] for r in paired])) for m in methods},
            "empty_cases": {m: sum(r[m]["empty_cloud"] for r in group) for m in methods},
            "all_samples": {m: summarize([r[m] for r in group]) for m in methods}}
    return output


@torch.no_grad()
def evaluate(args):
    stage1.DATA = args.data_root
    manifest = json.loads(args.manifest.read_text())
    rows = manifest["rows"]
    if manifest.get("split") != "test" or len(rows) != 512:
        raise ValueError("Expected the original fixed 512-start test manifest")
    trajectories = np.asarray([r["trajectory_indices"][:5] for r in rows], dtype=np.int64)
    flat = trajectories.reshape(-1)
    with h5py.File(args.data_root / "navrl_static_test.h5", "r") as h5:
        unique, inverse = np.unique(flat, return_inverse=True)
        actions = h5["normalized_action_sequence"][unique][inverse].reshape(512, 5, 10, 3)
        commands = h5["action_sequence"][unique][inverse].reshape(512, 5, 10, 3)
        targets = h5["range_values"][unique][inverse].reshape(512, 5, 2, 108, 20)
        starts = trajectories[:, 0]
        initial_frames = fetch(h5, "prev_range_values", starts)
        initial_states = fetch(h5, "prev_drone_state", starts).astype(np.float64)
        ego = stage1.causal_state(fetch(h5, "prev_ego_feats", starts))
    if not (np.isfinite(actions).all() and np.isfinite(commands).all() and
            np.isfinite(initial_states).all()):
        raise ValueError("Five-frame manifest contains nonfinite causal inputs")
    cached = stage1.Latents("test", stage1.OUT)
    lookup = {int(index): i for i, index in enumerate(cached.indices)}
    positions = [lookup[int(source)] for source in starts]
    initial_latents = cached.previous[positions]
    scale = json.loads((stage1.OUT / stage1.LATENT_DIR /
                        "metadata.json").read_text())["scaling_factor"]
    threshold = json.loads((stage1.OUT / stage1.CIRCULAR_VAE_DIR /
                            "oracle_val.json").read_text())["selected_threshold"]
    motion = load_motion(stage1.OUT / "epona_probe" / "motion_ridge.npz")
    model = stage1.WorldModel().to(stage1.DEVICE).float().eval()
    checkpoint = stage1.load_model(args.checkpoint, model)
    vae = stage1.load_circular_vae()
    scheduler = stage1.DDIMScheduler(num_train_timesteps=1000,
                                     prediction_type="epsilon", clip_sample=False)
    rays = {seed: load_rays(args.raw_root, "test", seed)
            for seed in sorted({row["seed"] for row in rows})}
    original_report = json.loads(args.original.read_text())
    original = {(r["source_index"], r["horizon"]): r["model"]
                for r in original_report["rows"]}
    output = []
    for seed in sorted(rays):
        locations = np.array([i for i, row in enumerate(rows) if row["seed"] == seed])
        ray_grid, azimuth, elevation = rays[seed]
        for batch_start in range(0, len(locations), args.batch_size):
            chosen = locations[batch_start:batch_start + args.batch_size]
            previous = initial_latents[chosen].to(stage1.DEVICE)
            frozen_ego = torch.from_numpy(ego[chosen]).to(stage1.DEVICE)
            predicted_states = initial_states[chosen].copy()
            for h in range(5):
                warped = []
                for j, index in enumerate(chosen):
                    predicted_states[j] = next_state(predicted_states[j],
                                                     commands[index, h], motion)
                    transform = transform_from_initial(initial_states[index],
                                                       predicted_states[j])
                    warped.append(warp_frame(initial_frames[index], transform,
                                             ray_grid, azimuth, elevation))
                warped = np.stack(warped)
                guide = vae.encode(torch.from_numpy(warped).to(
                    stage1.DEVICE)).latent_dist.mode() * scale
                action = torch.from_numpy(actions[chosen, h]).to(stage1.DEVICE)
                previous = stage1.generate(
                    model, scheduler, previous, action, frozen_ego,
                    seed=args.seed + seed * 10000 + batch_start + h * 100000,
                    init_strength=args.strength, num_steps=20,
                    initial_latent=guide)
                images = vae.decode(previous / scale).sample.cpu().numpy()
                for j, index in enumerate(chosen):
                    key = (rows[index]["source_index"], h + 1)
                    output.append({"source_index": key[0], "seed": seed,
                                   "horizon": h + 1,
                                   "guided_diffusion": lidar_metric(
                                       images[j], targets[index, h], ray_grid, threshold),
                                   "predicted_pose_warp": lidar_metric(
                                       warped[j], targets[index, h], ray_grid, 0),
                                   "original_diffusion": original[key]})
        print(json.dumps({"seed": seed, "starts": len(locations),
                          "completed_horizon": 5}), flush=True)
    methods = ("original_diffusion", "guided_diffusion", "predicted_pose_warp")
    comparison = {str(h): paired_summary(output, methods, h)
                  for h in range(1, 6)}
    result = {"version": 1, "split": "test", "starts": len(rows),
              "checkpoint_step": checkpoint["step"], "checkpoint": str(args.checkpoint),
              "strength_selected_on_one_step_validation": args.strength,
              "ddim_steps_per_frame": 20, "random_seed": args.seed,
              "causal_input": "initial observed frame/state and five recorded 10-step action chunks; generated latent recursively fed back; motion predictor uses only initial state and commands",
              "methods": methods, "comparison": comparison, "rows": output}
    save_json(args.output, result)
    print(json.dumps({"report": str(args.output),
                      "horizon_5": comparison["5"]["all"]}), flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--raw-root", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, default=stage1.OUT /
                        "representative_baseline" / "test_10frame_sample_manifest.json")
    parser.add_argument("--original", type=Path, default=stage1.OUT /
                        "representative_baseline" / "test_lagen_style_10frame_metrics.json")
    parser.add_argument("--checkpoint", type=Path, default=stage1.OUT /
                        "world_circular_causal_8h" / "best.pt")
    parser.add_argument("--output", type=Path, default=stage1.OUT /
                        "epona_probe" / "guided_diffusion" / "test_autoregressive_5.json")
    parser.add_argument("--strength", type=float, default=0.35)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    evaluate(args)


if __name__ == "__main__":
    main()
