"""Mix causal predicted geometry and history-latent priors before DDIM sampling.

The future LiDAR is always generated by the frozen diffusion UNet. Both priors
use only observations and executed commands available before the next frame.
"""

import argparse
import json
import sys
from pathlib import Path

import h5py
import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lidar_wam.runner import stage1
from lidar_wam.runner.epona_history import LidarHistoryMST
from lidar_wam.runner.lidar_geometry import load_rays, warp_frame
from evaluate_lagen_metrics_10 import lidar_metric, summarize
from evaluate_representative import fetch
from try_epona_guided_diffusion import load_motion
from try_epona_motion import next_state, transform_from_initial
from try_epona_mst_history import FiveHistoryDataset


def finite_geometry_subset(data, split, data_root, per_seed, random_seed):
    """Sample per seed only after checking finite executed commands."""
    with h5py.File(data_root / f"navrl_static_{split}.h5", "r") as h5:
        command = fetch(h5, "action_sequence", data.source)
        state = fetch(h5, "prev_drone_state", data.source)
    finite = np.isfinite(command).all(axis=(1, 2)) & np.isfinite(state).all(axis=1)
    rng = np.random.default_rng(random_seed)
    keep = np.concatenate([rng.choice(np.flatnonzero(finite & (data.seeds == seed)),
                                      per_seed, replace=False)
                           for seed in sorted(set(data.seeds))])
    candidates = {str(seed): int(np.sum(finite & (data.seeds == seed)))
                  for seed in sorted(set(data.seeds))}
    for name in ("source", "seeds", "history_source", "history", "previous",
                 "past_actions", "target", "future_actions", "state"):
        setattr(data, name, getattr(data, name)[keep])
    print(json.dumps({"split": split, "finite_candidates_per_seed": candidates,
                      "selected_samples": len(data)}), flush=True)
    return data


@torch.no_grad()
def evaluate(split, data, prior, unet, vae, motion, alphas, args, scale, threshold):
    with h5py.File(args.data_root / f"navrl_static_{split}.h5", "r") as h5:
        fields = {key: fetch(h5, key, data.source) for key in (
            "prev_drone_state", "action_sequence", "prev_range_values", "range_values")}
    rays = {int(seed): load_rays(args.raw_root, split, int(seed))
            for seed in sorted(set(data.seeds))}
    warped = []
    for i, seed in enumerate(data.seeds):
        state = fields["prev_drone_state"][i].astype(np.float64)
        command = fields["action_sequence"][i].astype(np.float64)
        predicted = next_state(state, command, motion)
        directions, azimuth, elevation = rays[int(seed)]
        warped.append(warp_frame(fields["prev_range_values"][i],
                                 transform_from_initial(state, predicted),
                                 directions, azimuth, elevation))
    warped = np.stack(warped)
    scheduler = stage1.DDIMScheduler(num_train_timesteps=1000,
                                     prediction_type="epsilon", clip_sample=False)
    methods = [f"mix_{a:g}" for a in alphas]
    rows = [{"source_index": int(src), "seed": int(seed)}
            for src, seed in zip(data.source, data.seeds)]
    for start in range(0, len(data), args.batch_size):
        stop = min(start + args.batch_size, len(data))
        history = data.history[start:stop].to(stage1.DEVICE)
        past = data.past_actions[start:stop].to(stage1.DEVICE)
        previous = history[:, -1]
        future_actions = data.future_actions[start:stop].to(stage1.DEVICE)
        state = data.state[start:stop].to(stage1.DEVICE)
        learned = prior(history, past)
        geometric = vae.encode(torch.from_numpy(warped[start:stop]).to(
            stage1.DEVICE)).latent_dist.mode() * scale
        images = {}
        for alpha in alphas:
            guide = geometric.lerp(learned, alpha)
            output = stage1.generate(unet, scheduler, previous, future_actions,
                                     state, seed=args.seed + start,
                                     init_strength=args.strength,
                                     num_steps=args.ddim_steps,
                                     initial_latent=guide)
            images[f"mix_{alpha:g}"] = vae.decode(output / scale).sample.cpu().numpy()
        for local, index in enumerate(range(start, stop)):
            ray = rays[int(data.seeds[index])][0]
            target = fields["range_values"][index]
            rows[index]["direct_warp"] = lidar_metric(warped[index], target, ray, 0)
            for method in methods:
                rows[index][method] = lidar_metric(images[method][local], target,
                                                   ray, threshold)
        print(json.dumps({"split": split, "evaluated": stop, "total": len(data)}),
              flush=True)
    methods = ["direct_warp", *methods]
    summaries = {}
    for group_name, group in (("all", rows), *(
            (f"seed_{seed}", [r for r in rows if r["seed"] == seed])
            for seed in sorted(set(data.seeds)))):
        paired = [r for r in group if all(not r[m]["empty_cloud"] for m in methods)]
        summaries[group_name] = {
            "samples": len(group), "paired_nonempty": len(paired),
            "paired_cd_paper_m2": {m: float(np.mean([r[m]["cd_paper_m2"]
                                                    for r in paired])) for m in methods},
            "all_samples": {m: summarize([r[m] for r in group]) for m in methods}}
    return {"split": split, "methods": methods, "summary": summaries, "rows": rows}


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--data-root", type=Path, required=True)
    p.add_argument("--raw-root", type=Path, required=True)
    p.add_argument("--prior-run", type=Path, default=stage1.OUT / "worldvln_latent_prior_1000")
    p.add_argument("--out", type=Path, default=stage1.OUT / "history_geometry_mix")
    p.add_argument("--motion", type=Path, default=stage1.OUT / "epona_probe" /
                   "motion_ridge.npz")
    p.add_argument("--unet", type=Path, default=stage1.OUT /
                   "world_circular_causal_8h" / "best.pt")
    p.add_argument("--per-seed", type=int, default=64)
    p.add_argument("--batch-size", type=int, default=16)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--strength", type=float, default=0.35)
    p.add_argument("--ddim-steps", type=int, default=20)
    p.add_argument("--alphas", type=float, nargs="+", default=[0, 0.25, 0.5, 0.75, 1])
    args = p.parse_args()
    if any(not 0 <= a <= 1 for a in args.alphas):
        p.error("alphas must be in [0,1]")
    args.out.mkdir(parents=True, exist_ok=True)
    stage1.DATA = args.data_root
    val = finite_geometry_subset(FiveHistoryDataset("val", args.data_root),
                                 "val", args.data_root, args.per_seed, args.seed)
    test = finite_geometry_subset(FiveHistoryDataset("test", args.data_root),
                                  "test", args.data_root, args.per_seed, args.seed)
    saved = torch.load(args.prior_run / "future_latent_best.pt", map_location="cpu",
                       weights_only=False)
    prior = LidarHistoryMST(width=saved["width"], blocks=saved["blocks"])
    prior.load_state_dict(saved["model"])
    prior = prior.to(stage1.DEVICE).float().eval()
    unet = stage1.WorldModel().to(stage1.DEVICE).float().eval()
    stage1.load_model(args.unet, unet)
    vae = stage1.load_circular_vae()
    motion = load_motion(args.motion)
    scale = json.loads((stage1.OUT / stage1.LATENT_DIR /
                        "metadata.json").read_text())["scaling_factor"]
    threshold = json.loads((stage1.OUT / stage1.CIRCULAR_VAE_DIR /
                            "oracle_val.json").read_text())["selected_threshold"]
    stage1.save_json(args.out / "config.json", {"prior_run": str(args.prior_run),
        "prior_step": saved["step"], "motion": str(args.motion),
        "unet": str(args.unet), "strength": args.strength,
        "ddim_steps": args.ddim_steps, "alphas": args.alphas,
        "per_seed": args.per_seed,
        "sampling": "seeded uniform among five-history rows with finite executed commands and state",
        "selection": "lowest paired validation Chamfer among diffusion variants"})
    validation = evaluate("val", val, prior, unet, vae, motion,
                          args.alphas, args, scale, threshold)
    stage1.save_json(args.out / "validation.json", validation)
    score = validation["summary"]["all"]["paired_cd_paper_m2"]
    chosen = min(args.alphas, key=lambda a: score[f"mix_{a:g}"])
    stage1.save_json(args.out / "selection.json", {"selected_alpha": chosen,
        "validation_paired_cd_paper_m2": score})
    print(json.dumps({"selected_alpha": chosen, "validation": score}), flush=True)
    tested = sorted({0.0, chosen, 1.0})
    result = evaluate("test", test, prior, unet, vae, motion, tested,
                      args, scale, threshold)
    stage1.save_json(args.out / "test.json", result)
    print(json.dumps({"test": result["summary"]["all"]["paired_cd_paper_m2"],
                      "paired_n": result["summary"]["all"]["paired_nonempty"]}),
          flush=True)


if __name__ == "__main__":
    main()
